create type category as enum('PHONE','LAPTOP','DESKTOP','AUDIO','TABLET','EARPHONE');

CREATE TABLE PRDT_INFO(
    PRDT_INFO_ID SERIAL PRIMARY KEY,
    PRDT_NAME VARCHAR(255) NOT NULL UNIQUE,
    PRDT_DESC TEXT,
    PRDT_TYPE category ,
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP
);

create type seller_source as enum('PCHOME','MOMO','SHOPEE','AMAZON','YAHOO','OTHER');

CREATE TABLE PRICE_INFO(
    PRICE_INFO_ID SERIAL PRIMARY KEY,
    PRDT_INFO_ID  INTEGER NOT NULL,
    PRICE NUMERIC(10,2),
    DISCOUNT NUMERIC(3),
    SOURCE_URL TEXT,
    SOURCE_TYPE seller_source ,
    DATA_DATE TIMESTAMP
);

CREATE TABLE USER_LIKES(
    PRDT_INFO_ID integer REFERENCES PRDT_INFO(PRDT_INFO_ID),
    USER_ID integer REFERENCES USER_INFO(USER_ID),
    PRIMARY KEY (PRDT_INFO_ID, USER_ID)
);